# Fetches counter ratings for every hero pair from counterwatch.gg and writes data/matchups.js.
# Value = how strongly the OTHER hero counters this hero (+ = this hero is countered, - = this hero wins).
# Usage:  powershell -ExecutionPolicy Bypass -File tools\update-matchups.ps1
param([string]$Only = "")
$ErrorActionPreference = "Stop"
$UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130 Safari/537.36"
$root = Split-Path $PSScriptRoot -Parent
$utf8 = New-Object Text.UTF8Encoding($false)

# hero ids from data/meta.js (OW.heroList)
$meta = [IO.File]::ReadAllText((Join-Path $root "data\meta.js"), $utf8)
$listBlock = [regex]::Match($meta, 'OW\.heroList = \[(.*?)\];', "Singleline").Groups[1].Value
$ids = [regex]::Matches($listBlock, '"([a-z0-9]+)"') | ForEach-Object { $_.Groups[1].Value }
if ($Only) { $ids = $ids | Where-Object { $_ -eq $Only } }

# counterwatch slug <-> our id
$slugOf = @{ junkerqueen = "junker-queen"; wreckingball = "wrecking-ball" }
function To-Id([string]$slug) { return $slug -replace "-", "" }

$out = [ordered]@{}
foreach ($id in $ids) {
  $slug = if ($slugOf[$id]) { $slugOf[$id] } else { $id }
  try {
    $res = Invoke-WebRequest -UseBasicParsing -UserAgent $UA "https://www.counterwatch.gg/stats/overwatch/counters/$slug"
  } catch { Write-Host ("{0,-14} skipped ({1})" -f $id, $_.Exception.Message); continue }
  $html = [Text.Encoding]::UTF8.GetString($res.RawContentStream.ToArray())
  $vals = [ordered]@{}
  foreach ($sec in [regex]::Matches($html, '<section aria-label="(Tank|Damage|Support) counters to [^"]*">(.*?)</section>', "Singleline")) {
    foreach ($e in [regex]::Matches($sec.Groups[2].Value, 'href="/stats/overwatch/heroes/([a-z0-9-]+)">(.*?)(?=href="/stats/overwatch/heroes/|$)', "Singleline")) {
      $text = [regex]::Replace($e.Groups[2].Value, "<[^>]+>", " ")
      $minus = [string][char]0x2212  # typographic minus sign used on the page
      $m = [regex]::Match($text, '(?<![\w.])([+\-' + $minus + ']?\d+\.\d)(?![\d])')
      if (-not $m.Success) { continue }
      $other = To-Id $e.Groups[1].Value
      if ($other -eq $id -or $vals.Contains($other)) { continue }
      $vals[$other] = [double]($m.Groups[1].Value -replace $minus, "-")
    }
  }
  $out[$id] = $vals
  Write-Host ("{0,-14} {1} opponents" -f $id, $vals.Count)
}

$json = [ordered]@{ fetched = (Get-Date).ToString("yyyy-MM-dd"); heroes = $out } | ConvertTo-Json -Depth 4 -Compress
$js = "// Generated by tools/update-matchups.ps1 - counterwatch.gg counter ratings (5v5, all ranks).`n" +
      "// heroes[a][b] = how strongly b counters a (+: a is countered by b, -: a beats b)`n" +
      "OW.matchupStats = $json;`n"
if (-not $Only) { [IO.File]::WriteAllText((Join-Path $root "data\matchups.js"), $js, $utf8); Write-Host "Wrote data/matchups.js" }
else { $json }
