# Fetches official hero statistics (win / pick / ban rate since the latest patch)
# from https://overwatch.blizzard.com/en-us/rates/ and writes data/stats.js.
# Usage:  powershell -ExecutionPolicy Bypass -File tools\update-stats.ps1
param(
  [string]$Platform = "PC",
  [string[]]$Regions = @("Asia", "Americas", "Europe"),
  [string]$Tier = "All"
)
$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Web
$UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130 Safari/537.36"
$modes = [ordered]@{ comp = 2; qp = 0 }
$out = Join-Path (Split-Path $PSScriptRoot -Parent) "data\stats.js"

$sets = [ordered]@{}
foreach ($m in $modes.Keys) {
  foreach ($r in $Regions) {
    $url = "https://overwatch.blizzard.com/en-us/rates/?input=$Platform&map=all-maps&region=$r&role=All&rq=$($modes[$m])&tier=$Tier"
    $res = Invoke-WebRequest -UseBasicParsing -UserAgent $UA $url
    $html = [Text.Encoding]::UTF8.GetString($res.RawContentStream.ToArray())
    $match = [regex]::Match($html, 'allrows="([^"]*)"')
    if (-not $match.Success) { throw "allrows not found: $url" }
    $rows = [System.Web.HttpUtility]::HtmlDecode($match.Groups[1].Value) | ConvertFrom-Json
    $set = [ordered]@{}
    foreach ($row in $rows) {
      $id = $row.id -replace "-", ""
      $set[$id] = @($row.cells.winrate, $row.cells.pickrate, $row.cells.banrate)
    }
    $sets["$m-$r"] = $set
    Write-Host ("{0,-14} {1} heroes" -f "$m-$r", $set.Count)
  }
}

$json = [ordered]@{
  fetched = (Get-Date).ToString("yyyy-MM-dd")
  input   = $Platform
  tier    = $Tier
  sets    = $sets
} | ConvertTo-Json -Depth 5 -Compress

$js = "// Generated by tools/update-stats.ps1 - official hero statistics since the latest patch.`n" +
      "// Each value: [win rate %, pick rate %, ban rate %]`n" +
      "OW.stats = $json;`n"
[IO.File]::WriteAllText($out, $js, (New-Object Text.UTF8Encoding($false)))
Write-Host "Wrote $out"
