# Fetches official hero statistics (win / pick / ban rate since the latest patch)
# from https://overwatch.blizzard.com/en-us/rates/ and writes:
#   data/stats.js     - all maps
#   data/mapstats.js  - per map (skipped with -SkipMaps)
# Usage:  powershell -ExecutionPolicy Bypass -File tools\update-stats.ps1 [-SkipMaps]
param(
  [string]$Platform = "PC",
  [string[]]$Regions = @("Asia", "Americas", "Europe"),
  [string]$Tier = "All",
  [switch]$SkipMaps
)
$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Web
$UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130 Safari/537.36"
$modes = [ordered]@{ comp = 2; qp = 0 }
$dataDir = Join-Path (Split-Path $PSScriptRoot -Parent) "data"
$utf8 = New-Object Text.UTF8Encoding($false)

function Get-RatesPage([string]$map, [string]$region, [int]$rq) {
  $url = "https://overwatch.blizzard.com/en-us/rates/?input=$Platform&map=$map&region=$region&role=All&rq=$rq&tier=$Tier"
  $res = Invoke-WebRequest -UseBasicParsing -UserAgent $UA $url
  return [Text.Encoding]::UTF8.GetString($res.RawContentStream.ToArray())
}

function Get-Rows([string]$html) {
  $match = [regex]::Match($html, 'allrows="([^"]*)"')
  if (-not $match.Success) { return $null }
  $rows = [System.Web.HttpUtility]::HtmlDecode($match.Groups[1].Value) | ConvertFrom-Json
  $set = [ordered]@{}
  foreach ($row in $rows) {
    $c = $row.cells
    # "--" (not enough data) becomes null
    $vals = @($c.winrate, $c.pickrate, $c.banrate) | ForEach-Object { if ($_ -is [string]) { $null } else { $_ } }
    $set[($row.id -replace "-", "")] = $vals
  }
  return $set
}

function Write-DataFile([string]$name, [string]$var, $obj, [string]$comment) {
  $json = $obj | ConvertTo-Json -Depth 6 -Compress
  $js = "// Generated by tools/update-stats.ps1 - $comment`n// Each value: [win rate %, pick rate %, ban rate %]`n$var = $json;`n"
  [IO.File]::WriteAllText((Join-Path $dataDir $name), $js, $utf8)
  Write-Host "Wrote data/$name"
}

# ---- all maps ----
$sets = [ordered]@{}
$firstHtml = $null
foreach ($m in $modes.Keys) {
  foreach ($r in $Regions) {
    $html = Get-RatesPage "all-maps" $r $modes[$m]
    if (-not $firstHtml) { $firstHtml = $html }
    $set = Get-Rows $html
    if (-not $set) { throw "allrows not found ($m-$r)" }
    $sets["$m-$r"] = $set
    Write-Host ("{0,-14} {1} heroes" -f "$m-$r", $set.Count)
  }
}
$fetched = (Get-Date).ToString("yyyy-MM-dd")
Write-DataFile "stats.js" "OW.stats" ([ordered]@{ fetched = $fetched; input = $Platform; tier = $Tier; sets = $sets }) "official hero statistics since the latest patch."

if ($SkipMaps) { return }

# ---- per map ----
$i = $firstHtml.IndexOf('filter-map-select'); $j = $firstHtml.IndexOf('</select>', $i)
$maps = [regex]::Matches($firstHtml.Substring($i, $j - $i), 'value="([^"]+)"') |
  ForEach-Object { $_.Groups[1].Value } | Where-Object { $_ -ne "all-maps" }
$mapSets = [ordered]@{}
foreach ($map in $maps) {
  $mapSets[$map] = [ordered]@{}
  foreach ($m in $modes.Keys) {
    foreach ($r in $Regions) {
      $set = Get-Rows (Get-RatesPage $map $r $modes[$m])
      if ($set) { $mapSets[$map]["$m-$r"] = $set }
    }
  }
  Write-Host ("{0,-22} {1} sets" -f $map, $mapSets[$map].Count)
}
Write-DataFile "mapstats.js" "OW.mapStats" ([ordered]@{ fetched = $fetched; input = $Platform; tier = $Tier; maps = $mapSets }) "official hero statistics per map since the latest patch."
